Bug fixes and improvements
yggdrasil-network/crispa-android pull request #39
Opened 2020-12-09 13:13 UTC by vikulin

1. bug fixes and improvements:
    #7, #30, #32, #38, #36
2. Yggdrasil core new build

2020-12-14 06:36 UTC, ChronosX88 requested changes

2020-12-14 06:36 UTC, ChronosX88 commented on app/src/main/res/layout/content_node_info.xml
> +    <ListView
ListView is deprecated, why you don't use RecycleView?

2020-12-21 06:31 UTC, vikulin commented on app/src/main/res/layout/content_node_info.xml
> +    <ListView
I reviewed necessary changes to migrate from ListView to RecycleView and believe it is too wide involving internal listeners refactoring. Can we do this in next optimization iteration?

2020-12-28 15:58 UTC, ChronosX88 approved these changes

2020-12-28 15:58 UTC, merged