0.4 yggdrasil main routing changes
yggdrasil-network/crispa-android pull request #53
Opened 2021-06-26 17:01 UTC by vikulin

1. 0.4 yggdrasil main routing changes
2. Fix for #48 
3. App package renamed

2021-07-18 12:22 UTC, cofob approved these changes
👍

2021-07-18 12:23 UTC, Revertron commented on app/src/androidTest/java/org/yggdrasil/app/crispa/ExampleInstrumentedTest.kt
> +package org.yggdrasil.app.crispa
Do you own domain yggdrasil.org? Or maybe you've got a permission from it's owner?
If not, it is better to change package name to domains owned by Neil or someone from our group.
You may use my domain, if you like: `link.yggdrasil.crispa`.
Or: `io.github.yggdrasil-network.crispa`.

2021-07-18 12:25 UTC, Revertron commented on app/src/main/java/org/yggdrasil/app/crispa/PeerListActivity.kt
> +        const val PEER_LIST_URL = "http://y4.rivchain.org/rest/peers.json"
This URL will be loaded through clearnet, why without HTTPS?

2021-07-18 12:26 UTC, Revertron commented on app/src/main/java/org/yggdrasil/app/crispa/YggApplication.kt
> +                basicAuthPassword = "F4cCIqo9EjpihcPt"
Are there no tokens for clients? Including passwords in source code is very bad practice.

2021-07-18 12:27 UTC, Revertron commented on app/src/main/java/org/yggdrasil/app/crispa/YggdrasilTunService.kt
> +        ACRA.errorReporter.putCustomData("Peers JSON", ygg.peersJSON)
Including user's peer list should be an opt-in configurable option. Peers maybe private.

2021-07-18 12:35 UTC, cofob commented on app/src/main/java/org/yggdrasil/app/crispa/PeerListActivity.kt
> +        const val PEER_LIST_URL = "http://y4.rivchain.org/rest/peers.json"
+1

Why not use official (neilalexander) peers.json?

2021-07-18 18:27 UTC, vikulin commented on app/src/main/java/org/yggdrasil/app/crispa/PeerListActivity.kt
> +        const val PEER_LIST_URL = "http://y4.rivchain.org/rest/peers.json"
> 
> 
> +1
> 
> Why not use official (neilalexander) peers.json?

The Neil's peer parser is not opensource.

2021-07-18 18:27 UTC, vikulin commented on app/src/main/java/org/yggdrasil/app/crispa/PeerListActivity.kt
> +        const val PEER_LIST_URL = "http://y4.rivchain.org/rest/peers.json"
> 
> 
> This URL will be loaded through clearnet, why without HTTPS?

Will be added https in next release.

2021-07-18 18:47 UTC, vikulin commented on app/src/main/java/org/yggdrasil/app/crispa/YggApplication.kt
> +                basicAuthPassword = "F4cCIqo9EjpihcPt"
I worse scenario it will affect only reporting backend not app.

2021-07-18 18:49 UTC, vikulin commented on app/src/androidTest/java/org/yggdrasil/app/crispa/ExampleInstrumentedTest.kt
> +package org.yggdrasil.app.crispa
> 
> 
> Do you own domain yggdrasil.org? Or maybe you've got a permission from it's owner?
> If not, it is better to change package name to domains owned by Neil or someone from our group.
> You may use my domain, if you like: `link.yggdrasil.crispa`.
> Or: `io.github.yggdrasil-network.crispa`.

I don't see any issues with yggdrasil.org domain in package name. @neilalexander , any ideas?

2021-11-22 06:33 UTC, bbigras commented
Any progress on this?

2021-11-22 07:52 UTC, vikulin commented
@bbigras I will merge it as soon anyone confirm that the core yggdrasil 0.4 in good state and no crashes occurs in crispa.

2022-01-15 14:17 UTC, ChronosX88 requested changes

2022-01-15 14:17 UTC, ChronosX88 commented on app/src/main/java/org/yggdrasil/app/crispa/YggApplication.kt
> +                basicAuthPassword = "F4cCIqo9EjpihcPt"
That should be in separate .properties file

2022-01-15 14:20 UTC, merged